programs:
  - code: sleep
    emoji: "ğŸ˜´"
    color: "#a996ff"
  - code: play
    emoji: "âš½ï¸"
    color: "#c2edc8"
  - code: eat
    emoji: "ğŸ²"
    color: "#fac8f8"
  - code: walk
    emoji: "ğŸš¶"
    color: "#b3f1ff"
  - code: shower
    emoji: "ğŸš¿"
    color: "#ffffff"
schedule:
  - code: play
    start: "06:30"
  - code: eat
    start: "07:00"
  - code: play
    start: "08:20"
  - code: sleep
    start: "11:30"
  - code: eat
    start: "12:30"
  - code: play
    start: "13:00"
  - code: eat
    start: "17:00"
  - code: play
    start: "18:00"
  - code: shower
    start: "19:30"
  - code: sleep
    start: "20:00"
